### PR TITLE
Add Redis providers for Orleans 2.0

### PR DESCRIPTION
**Pull request by glacorSoul**

### CODE REVIEW

**Comment by Arshia001** [comment]
I can see Redis being used for clustering, but grain storage? Orleans already keeps all data in memory, to me it makes zero sense to have a second copy of all data in memory at the same time. Or is there something I'm not seeing?

**Comment by brunoss** [comment]
@Arshia001 Grain state can and should be stored in a persistent manner so Grains can recover their data in case the machine dies.

**Comment by Arshia001** [comment]
Yes, but it should be stored primarily on disk. Redis stores all data in memory to keep it close at hand for increased read throughput. Orleans on the other hand also keeps all the stuff close at hand in memory too.

**Comment by richorama** [comment]
@Arshia001 I agree with your observation, that redis is an odd choice for orleans, but I’ve found it a reasonably popular option. Peoples use cases vary. It could work very well for dev/test scenarios for example. 

@brunoss Thanks for the PR, I’ll review in a day or so. :-)

**Comment by Arshia001** [comment]
@richorama there should probably be a warning somewhere that Redis is not the best choice for production.

**Comment by brunoss** [comment]
@Arshia001 As far as I know Redis can also store data in the disk as long as it configured to do so.

**Comment by Arshia001** [comment]
@brunoss true. However, the disk is only used for restarts and disaster recovery. Redis is (and always will be) only as good as your RAM.

**Comment by richorama** [comment]
@brunoss quick question, does this provider maintain backward compatibility with the previous verison?

**Comment by brunoss** [comment]
@richorama I haven't tries this on Orleans 1.x. My idea was to release a different nugget package just for 2.0. But I will try to provide more information regarding compatibility when I can.

**Comment by brunoss** [comment]
@richorama At a first look it seems the Orleans grain references have changed between 1.5 and 2.0. Which means none of the grains are compatible in case you are storing them by grain reference.

I will see if there is a way to keep things compatible somehow.

**Comment by amccool** [comment]
see #27

**Pull request closed without merging**
