### PR TITLE
Switch from Json.net to OrleansSerializationManager

### PR DESCRIPTION
**Pull request by amccool**
The json.net serializer into GrainState.Set has issues, amongst them is int moving to int64 and not deserializing back to Int32 properly.
see https://github.com/dotnet/orleans/issues/1269

Changing the serializer to Orleans.Serialization.SerializationManager (binary) seems to circumvent these issues.

I added a useJsonformat property to the configuration (same as AzureTableStore).  It defaults to the Orleans.Serialization.SerializationManager, but can be set to use json.net

The unit tests are highly questionable.
1. They need to be run twice to cause the Read to fail (existing state)
2. I cant get the PubSubStore to Read, as the Clear cleans things out

I suggest asking for an improvement on the unit tests

### CODE REVIEW

**Comment by richorama** [comment]
@amccool this looks ready to merge. Shall I press the button??

**Comment by amccool** [comment]
I have a private nuget for my shop(so my urgency is diminished).  My shop will test this in a loaded environment tomorrow.  

The big problem is existing data will become unreadable (json->binary) so people will need to clear their state.

**Comment by richorama** [comment]
I wonder whether we should set the default to be the JSON serializer to maintain backward compatibility, and give notice that the binary serializer is preferred..

**Comment by richorama** [comment]
PS, is your shop clown related? (please say yes)

**Comment by amccool** [comment]
actually its healthcare - so yes

**Comment by amccool** [comment]
@richorama posted are final changes to allow for the default to be json.  I believe the PR is complete now.   It might be of note, perhaps in the readme.md to state that using json serializer has problems with certain grainstates especially PubSubStore

**Comment by richorama** [comment]
thank you @amccool! I'll update the readme...

**Pull request merged**
